In [3]:
import torch
from torch.utils import data
import math
import random
import numpy as np
import matplotlib.pyplot as plt
from torch import nn
import torch.nn.functional as F

#### 通过数学运算，自定义网络结构

In [10]:
class MyLinear(nn.Module):
    def __init__(self, in_units, out_units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn((in_units, out_units)))
        self.bias = nn.Parameter(torch.randn(out_units,))
        
    def forward(self, x):
        linear = torch.matmul(x, self.weight.data) + self.bias.data
        out_data = F.rlue(linear)
        return out_data
        

In [11]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 1.1691, -0.3463, -1.4775],
        [-0.4148, -0.8804,  0.1253],
        [ 0.1424, -0.2709, -1.3324],
        [-0.3739, -0.1439,  0.6848],
        [-0.3387,  0.2602,  0.9950]], requires_grad=True)

In [7]:
linear(torch.randn(2,5))

tensor([[3.7398, 0.0000, 3.1745],
        [2.4685, 4.6450, 0.3718]])

In [8]:
net = nn.Sequential(MyLinear(64,32), MyLinear(32,1))
net(torch.randn(2,64))

tensor([[1.5320],
        [0.0000]])

In [12]:
torch.save(net.state_dict(), "mlp.params")

In [13]:
net2 = nn.Sequential(MyLinear(64,32), MyLinear(32,1))
net2.load_state_dict(torch.load("mlp.params"))

<All keys matched successfully>

In [14]:
net2.eval()

Sequential(
  (0): MyLinear()
  (1): MyLinear()
)

In [15]:
torch.device("cpu"),torch.device("cuda")

(device(type='cpu'), device(type='cuda'))

In [16]:
torch.cuda.device_count()

0

In [17]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [21]:
def try_gpu(i=0): 
    if torch.cuda.device_count() >= i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')


In [22]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
try_gpu()

device(type='cpu')