In [5]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np

In [8]:
data_path = r"G:\data\HW3_CNN"
train_x_file= "train_11.npy"
train_y_file = "train_label_11.npy"
x_data = os.path.join(data_path, train_x_file)
y_data = os.path.join(data_path, train_y_file)

In [17]:
# x = np.load(y_data, rows=100)  x too large, cannot load
y = np.load(y_data)

In [1]:
from tensorflow.keras.layers import Conv2D, Dense, BatchNormalization,Activation,MaxPool2D,Dropout,Flatten
from  tensorflow.keras import Model, Sequential

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 页面文件太小，无法完成操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program

TypeError: must be str, not list

In [53]:
class ConvBNRelu(Model):
    def __init__(self, ch, kernelsz=3, stride=1, padding="same"):
        super(ConvBNRelu, self).__init__()
        self.model = Sequential([Conv2D(filters=ch, kernel_size=kernelsz, strides=stride, padding=padding),
            BatchNormalization(),
            Activation('relu'),
            MaxPool2D(pool_size=(2,2), strides=2, padding="same"),
            Dropout(0.2),
            Flatten(),
            Dense(128, activation="relu"),
            Dropout(0.2),
            Dense(1, activation="softmax")]
        )
    def call(self, x):
        x = self.model(x)
        return x
    

In [57]:
ConvBNRelu_model = ConvBNRelu(10)
ConvBNRelu_model.compile(optimizer="adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
                        metrics=["accuracy"])

In [60]:
ConvBNRelu_model

In [ ]:
ans = ConvBNRelu.predict(x_test)

In [100]:
import pathlib
from pathlib import Path
import glob

In [128]:
data_path = r"G:\data"

In [191]:
a = tf.data.Dataset.from_tensor_slices(np.random.uniform(size=(5, 2))) 
for i in a:
    print(i)

tf.Tensor([0.51119979 0.87707789], shape=(2,), dtype=float64)
tf.Tensor([0.32002503 0.39916415], shape=(2,), dtype=float64)
tf.Tensor([0.37921178 0.08345415], shape=(2,), dtype=float64)
tf.Tensor([0.70056914 0.11160623], shape=(2,), dtype=float64)
tf.Tensor([0.93367157 0.48196688], shape=(2,), dtype=float64)


In [188]:
img_path = r"G:\data\GBDT\images\a.jpeg"
all_image_paths.append(img_path)
# img_path = Path(img_path)
# all_image_paths = []
# for i in img_path.glob("*\\"):
    
ds = tf.data.Dataset.from_tensor_slices(all_image_paths)
# train_data = ds.map(load_and_preprocess_image).batch(16)
for i in ds:
    print(i)
    a = tf.io.read_file(i)
#     break
#     image = tf.image.decode_jpeg(image, channels=3)
#     image = tf.image.resize(image, [100, 100])
#     image /= 255.0 # normalize to [0,1] range
#     # image = tf.reshape(image,[100*100*3])
#     return image

tf.Tensor(b'G:\\data\\GBDT\\images\\a.jpeg', shape=(), dtype=string)


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 76: invalid continuation byte

In [182]:
tf.io.read_file?

Signature: tf.io.read_file(filename, name=None)
Docstring:
Reads the contents of file.

This operation returns a tensor with the entire contents of the input
filename. It does not do any parsing, it just returns the contents as
they are. Usually, this is the first step in the input pipeline.

Example:

>>> with open("/tmp/file.txt", "w") as f:
...   f.write("asdf")
...
4
>>> tf.io.read_file("/tmp/file.txt")
<tf.Tensor: shape=(), dtype=string, numpy=b'asdf'>

Example of using the op in a function to read an image, decode it and reshape
the tensor containing the pixel data:

>>> @tf.function
... def load_image(filename):
...   raw = tf.io.read_file(filename)
...   image = tf.image.decode_png(raw, channels=3)
...   # the `print` executes during tracing.
...   print("Initial shape: ", image.shape)
...   image.set_shape([28, 28, 3])
...   print("Final shape: ", image.shape)
...   return image

Args:
  filename: string. filename to read from.
  name: string.  Optional name for the op.

Retur

In [102]:
for i in data_path.iterdir():
    print(i)

G:\data\HW3_CNN\test_11.npy
G:\data\HW3_CNN\train_11.npy
G:\data\HW3_CNN\train_label_11.npy


In [89]:
Path(str("G:\data\HW3_CNN\test_11.npy")).suffix

'.npy'

In [236]:
import pandas as pd
df = pd.DataFrame([[1, 1, 2], [1, 2, 3], [2, 3, 4]], columns=["A", "B", "C"])
# df["key"] = ["A","A","B"]
df

A  B  C
0  1  1  2
1  1  2  3
2  2  3  4

In [216]:
A = df.groupby("key")["A","B"].mean().reset_index()
A

key    A    B
0   A  1.0  1.5
1   B  2.0  3.0

In [229]:
df.groupby("key").transform(np.mean).reset_index()

index  A    B    C
0      0  1  1.5  2.5
1      1  1  1.5  2.5
2      2  2  3.0  4.0

In [237]:
df.transform(lambda x :x+1)

A  B  C
0  2  2  3
1  2  3  4
2  3  4  5